#------------------------------------------------------------------------
# Source File Information (DO NOT MODIFY)
# Source ID: 641957f1-ef94-416b-a8f8-1549c2f3ed93
# Source File: C:\Users\Administrator\Documents\SAPIEN\PowerShell Studio 2015\Files\Query-Addon.psf
#------------------------------------------------------------------------

<#
    .NOTES
    --------------------------------------------------------------------------------
     Code generated by:  SAPIEN Technologies, Inc., PowerShell Studio 2015 v4.2.81
     Generated on:       12/8/2015 9:24 AM
     Generated by:       Administrator
    --------------------------------------------------------------------------------
    .DESCRIPTION
        GUI script generated by PowerShell Studio 2015
#>
#----------------------------------------------
#region Application Functions
#----------------------------------------------

#endregion Application Functions

#----------------------------------------------
# Generated Form Function
#----------------------------------------------
function Call-Query-Addon_psf {

	#----------------------------------------------
	#region Import the Assemblies
	#----------------------------------------------
	[void][reflection.assembly]::Load('mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	[void][reflection.assembly]::Load('System.Xml, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.DirectoryServices, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	[void][reflection.assembly]::Load('System.Core, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.ServiceProcess, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	#endregion Import Assemblies

	#----------------------------------------------
	#region Generated Form Objects
	#----------------------------------------------
	[System.Windows.Forms.Application]::EnableVisualStyles()
	$formIEAddonQueryToolV10 = New-Object 'System.Windows.Forms.Form'
	$buttonBrowse = New-Object 'System.Windows.Forms.Button'
	$richtextboxLogger = New-Object 'System.Windows.Forms.RichTextBox'
	$buttonQueryAddons = New-Object 'System.Windows.Forms.Button'
	$textboxComputerName = New-Object 'System.Windows.Forms.TextBox'
	$linklabelDenversacheznomuraco = New-Object 'System.Windows.Forms.LinkLabel'
	$label = New-Object 'System.Windows.Forms.Label'
	$InitialFormWindowState = New-Object 'System.Windows.Forms.FormWindowState'
	#endregion Generated Form Objects

	#----------------------------------------------
	# User Generated Script
	#----------------------------------------------
	
	$formIEAddonQueryToolV10_Load={
		#TODO: Initialize Form Controls here
		$richtextboxLogger.Clear()
	}
	
	$buttonQueryAddons_Click={
		#TODO: Place custom script here
		$ComputerName = $textboxComputerName.Text
		& c:\Temp\Autoruns\PsExec.exe \\$ComputerName c:\Temp\Autoruns\autorunsc.exe -accepteula -a i -c > c:\Temp\Autoruns\output.tsv
		$richtextboxLogger.Text += "$ComputerName : Script has ran successfully.", "`n"
	}
	
	$buttonBrowse_Click={
		#TODO: Place custom script here
		ii c:\temp\Autoruns
	}
	
	# --End User Generated Script--
	#----------------------------------------------
	#region Generated Events
	#----------------------------------------------
	
	$Form_StateCorrection_Load=
	{
		#Correct the initial state of the form to prevent the .Net maximized form issue
		$formIEAddonQueryToolV10.WindowState = $InitialFormWindowState
	}
	
	$Form_Cleanup_FormClosed=
	{
		#Remove all event handlers from the controls
		try
		{
			$buttonBrowse.remove_Click($buttonBrowse_Click)
			$buttonQueryAddons.remove_Click($buttonQueryAddons_Click)
			$formIEAddonQueryToolV10.remove_Load($formIEAddonQueryToolV10_Load)
			$formIEAddonQueryToolV10.remove_Load($Form_StateCorrection_Load)
			$formIEAddonQueryToolV10.remove_FormClosed($Form_Cleanup_FormClosed)
		}
		catch [Exception]
		{ }
	}
	#endregion Generated Events

	#----------------------------------------------
	#region Generated Form Code
	#----------------------------------------------
	$formIEAddonQueryToolV10.SuspendLayout()
	#
	# formIEAddonQueryToolV10
	#
	$formIEAddonQueryToolV10.Controls.Add($buttonBrowse)
	$formIEAddonQueryToolV10.Controls.Add($richtextboxLogger)
	$formIEAddonQueryToolV10.Controls.Add($buttonQueryAddons)
	$formIEAddonQueryToolV10.Controls.Add($textboxComputerName)
	$formIEAddonQueryToolV10.Controls.Add($linklabelDenversacheznomuraco)
	$formIEAddonQueryToolV10.Controls.Add($label)
	$formIEAddonQueryToolV10.ClientSize = '337, 328'
	$formIEAddonQueryToolV10.Name = "formIEAddonQueryToolV10"
	$formIEAddonQueryToolV10.Text = "IE Add-on Query Tool v1.0"
	$formIEAddonQueryToolV10.add_Load($formIEAddonQueryToolV10_Load)
	#
	# buttonBrowse
	#
	$buttonBrowse.Location = '237, 55'
	$buttonBrowse.Name = "buttonBrowse"
	$buttonBrowse.Size = '88, 23'
	$buttonBrowse.TabIndex = 5
	$buttonBrowse.Text = "Browse"
	$buttonBrowse.UseVisualStyleBackColor = $True
	$buttonBrowse.add_Click($buttonBrowse_Click)
	#
	# richtextboxLogger
	#
	$richtextboxLogger.Location = '13, 89'
	$richtextboxLogger.Name = "richtextboxLogger"
	$richtextboxLogger.Size = '312, 204'
	$richtextboxLogger.TabIndex = 4
	$richtextboxLogger.Text = ""
	#
	# buttonQueryAddons
	#
	$buttonQueryAddons.Location = '139, 55'
	$buttonQueryAddons.Name = "buttonQueryAddons"
	$buttonQueryAddons.Size = '92, 23'
	$buttonQueryAddons.TabIndex = 3
	$buttonQueryAddons.Text = "Query Addons"
	$buttonQueryAddons.UseVisualStyleBackColor = $True
	$buttonQueryAddons.add_Click($buttonQueryAddons_Click)
	#
	# textboxComputerName
	#
	$textboxComputerName.Location = '13, 58'
	$textboxComputerName.Name = "textboxComputerName"
	$textboxComputerName.Size = '120, 20'
	$textboxComputerName.TabIndex = 2
	$textboxComputerName.Text = "Hostname"
	#
	# linklabelDenversacheznomuraco
	#
	$linklabelDenversacheznomuraco.Location = '12, 304'
	$linklabelDenversacheznomuraco.Name = "linklabelDenversacheznomuraco"
	$linklabelDenversacheznomuraco.Size = '152, 23'
	$linklabelDenversacheznomuraco.TabIndex = 1
	$linklabelDenversacheznomuraco.TabStop = $True
	$linklabelDenversacheznomuraco.Text = "denver.sachez@nomura.com"
	#
	# label
	#
	$label.Location = '13, 13'
	$label.Name = "label"
	$label.Size = '312, 42'
	$label.TabIndex = 0
	$label.Text = "This will query the IE addons on remote machine. Start by typing the hostname. Then, click on Query Addons."
	$formIEAddonQueryToolV10.ResumeLayout()
	#endregion Generated Form Code

	#----------------------------------------------

	#Save the initial state of the form
	$InitialFormWindowState = $formIEAddonQueryToolV10.WindowState
	#Init the OnLoad event to correct the initial state of the form
	$formIEAddonQueryToolV10.add_Load($Form_StateCorrection_Load)
	#Clean up the control events
	$formIEAddonQueryToolV10.add_FormClosed($Form_Cleanup_FormClosed)
	#Show the Form
	return $formIEAddonQueryToolV10.ShowDialog()

} #End Function

#Call the form
Call-Query-Addon_psf | Out-Null
